export const personalData = [
    {
        "id": 1,
        "likes": 20,
        "group": "1",
        "title": "물티슈 나눔",
        "apply": "2024.12.08",
        "period": "명신관",
    },
    {
        "id": 2,
        "likes": 19,
        "group": "2",
        "title": "휴지 나눔",
        "apply": "2024.12.08",
        "period": "눈꽃광장",
    },
    {
        "id": 3,
        "likes": 18,
        "group": "3",
        "title": "쿠키 나눔",
        "apply": "2024.12.08",
        "period": "순헌관 1층",
    },
    {
        "id": 4,
        "likes": 17,
        "group": "4",
        "title": "생활용품 나눔",
        "apply": "2024.12.08",
        "period": "중앙도서관",
    },
    {
        "id": 5,
        "likes": 16,
        "group": "5",
        "title": "그림 그려줍니다",
        "apply": "2024.12.08",
        "period": "학생회관",
    },
    {
        "id": 6,
        "likes": 15,
        "group": "6",
        "title": "청파장터",
        "apply": "2024.12.08(목) ~",
        "period": "기숙사",
    },
    {
        "id": 7,
        "likes": 14,
        "group": "7",
        "title": "소웨 전공책 나눔",
        "apply": "2024.12.08",
        "period": "중앙도서관",
    },
    {
        "id": 8,
        "likes": 13,
        "group": "8",
        "title": "물티슈 나눔",
        "apply": "2024.12.08",
        "period": "중앙도서관",
    },
    {
        "id": 9,
        "likes": 12,
        "group": "9",
        "title": "휴지 나눔",
        "apply": "2024.12.08",
        "period": "중앙도서관",
    },
    {
        "id": 10,
        "likes": 11,
        "group": "10",
        "title": "과자 나눔합니다",
        "apply": "2024.12.08",
        "period": "중앙도서관",
    },
    {
        "id": 11,
        "likes": 10,
        "group": "11",
        "title": "소소한 이벤트",
        "apply": "2024.12.08",
        "period": "중앙도서관",
    },
    {
        "id": 12,
        "likes": 9,
        "group": "12",
        "title": "책 읽는 모임에서 이벤트",
        "apply": "2024.12.08",
        "period": "중앙도서관",
    },
    {
        "id": 13,
        "likes": 8,
        "group": "13",
        "title": "벨리곰 나눔",
        "apply": "2024.12.08",
        "period": "중앙도서관",
    },
    {
        "id": 14,
        "likes": 7,
        "group": "14",
        "title": "안 입는 옷 팝니다",
        "apply": "2024.12.08",
        "period": "중앙도서관",
    },
    {
        "id": 15,
        "likes": 6,
        "group": "15",
        "title": "전공책 나눔합니다",
        "apply": "2024.12.08",
        "period": "중앙광장",
    },
    {
        "id": 16,
        "likes": 5,
        "group": "16",
        "title": "학잠 나눔해요",
        "apply": "2024.12.08",
        "period": "눈꽃광장",
    },
    {
        "id": 17,
        "likes": 4,
        "group": "17",
        "title": "필기구 나눔해요",
        "apply": "2024.12.08",
        "period": "중앙도서관",
    },
    {
        "id": 18,
        "likes": 3,
        "group": "18",
        "title": "책 나눔합니다",
        "apply": "2024.12.08",
        "period": "눈꽃광장",
    },
    {
        "id": 19,
        "likes": 2,
        "group": "19",
        "title": "중도에서 이벤트",
        "apply": "2024.12.08",
        "period": "명신관",
    },
    {
        "id": 20,
        "likes": 1,
        "group": "20",
        "title": "생활용품 가져가세요",
        "apply": "2024.12.08",
        "period": "정문",
    }
]